name: Build and Deploy
on:
    push:
        branches:
            -   main

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@master
            -   name: Setup Enviroment
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8'
                    ini-values: memory_limit=-1
            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    version: 2
                    dev: no
            -   name: Install Packages
                run: sudo composer install --no-dev
            -   name: Deploy to Server
                uses: ngocquyhoang/deploy@laravel
                with:
                    user: ${{ secrets.user }}
                    host: ${{ secrets.host }}
                    path: ${{ secrets.deploymentPath }}
                env:
                    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
