name: CD

on:
  push:
      branches: [ main ]

jobs:
    deploy:
          runs-on: ubuntu-latest
          steps:
              -   uses: actions/checkout@v2
              -   name: Deploy to production
                  uses: appleboy/ssh-action@master
                  with:
                      username: root
                      host: 66.29.130.69
                      password: ${{ secrets.SSH_PASSWORD }}
                      script: './deploy_setup.sh'
