name: CD

on:
  push:
      branches: [ main ]

jobs:
    deploy:
          runs-on: ubuntu-latest
          steps:
              -   uses: actions/checkout@v2
                  with:
                      token: ${{ secrets.PUSH_TOKEN }}
              -   name: Deploy to production
                  uses: appleboy/ssh-action@master
                  with:
                      username: ${{ secrets.username }}
                      host: ${{ secrets.host }}
                      password: ${{ secrets.SSH_PASSWORD }}
                      passphrase: ${{ secrets.pass }}
                      script: 'cd public_html; rm -rf api; git clone https://github.com/khorramk/mat-backend.git api;
                      cp .env api/;
                      cd api && composer install'

